export enum OrderStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  RIDER_ASSIGNED = "RIDER_ASSIGNED",
  PREPARING = "PREPARING",
  READY = "READY",
  PICKED = "PICKED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}
